// Names generated by http://chir.ag/projects/name-that-color/

export default {
  BRIGHT_GRAY: "#393F4B",
  RIVER_BED: "#434A58",
  GRAY_NICKEL: "#C0C1BF",
  SHUTTLE_GRAY: "#545D6E",
  NEVADA: "#6B6F77",
  WHITE: "#FFFFFF"
};
